export const songArtist = [
{ song:'AFTER MIDNIGHT', by:'Eric Clapton'},
{ song:'ALABAMA GETAWAY', by:'Grateful Dead' },
{ song:'ANGEL FROM MONTGOMERY', by:'John Prine' },
{ song:'BROWN EYED WOMEN', by:'Grateful Dead' },
{ song:'CASEY JONES', by:'Grateful Dead '},
{ song:'CITY OF NEW ORLEANS ', by:'Steve Goodman/Arlo Guthrie' },
{ song:'COME TOGETHER', by:'Beatles' },
{ song:'DEAL', by:'Grateful Dead' },
{ song:'DONE SOMEBODY WRONG', by:'Allman Brothers' },
{ song:'FEELIN’ ALLRIGHT', by:'Joe Cocker' },
{ song:'FOLSOM PRISON BLUES', by:'Johnny Cash' },
{ song:'FRIEND OF THE DEVIL', by:'Grateful Dead '},
{ song:'HERE COMES THE SUN', by:'Beatles' },
{ song:'I KNOW A LITTLE', by:'Lynrd Skynrd' },
{ song:'IT’S ONLY ROCK N’ ROLL', by:'Rolling Stones ' },
{ song:'MAGIC CARPET RIDE', by:'Steppenwolf '},
{ song:'NOBODY KNOWS YOU WHEN YOU’RE DOWN AND OUT', by:'Eric Clapton '},
{ song:'NOT FADE AWAY', by:'Buddy Holly/Grateful Dead '},
{ song:'OB-LA-DI, OB-LA-DA', by:'Beatles' },
{ song:'ONE WAY OUT', by:'Allman Brothers' },
{ song:'OPHELIA', by:'The Band '},
{ song:'PIANO MAN', by:'Billy Joel' },
{ song:'THE RACE IS ON', by:'George Jones/Sawyer Brown '},
{ song:'RIPPLE', by:'Grateful Dead '},
{ song:'SOME KIND OF WONDERFUL', by:'Grand Funk Railroad' },
{ song:'TELL IT LIKE IT IS', by:'Aaron Neville' },
{ song:'TENNESSEE WHISKEY', by:'Chris Stapleton'},
{ song:'TEQUILA SUNRISE', by:'Eagles' },
{ song:'TWO PINA COLADAS', by:'Garth Brooks' },
{ song:'WALK ON THE WILD SIDE', by:'Lou Reed' },
{ song:'WATCHING THE RIVER FLOW', by:'Bob Dylan' },
{ song:'WHAT A WONDERFUL WORLD', by:'Louis Armstrong' },
{ song:'YELLOW MOON', by:'Neville Brothers' },
];